### ISSUE TITLE
apache fastcgi protocol

### ISSUE THREAD

**Issue by Announcement** [samcday/node-fastcgi-stream#6]
nodejs can receive apache fastcgi requests like this
```
process.stdin.on('data', function (it) {
```
how do i decode the fastcgi request data? that's what this library is for, but it's very unclear how to use it.

**Comment by samcday** [comment]
Hiya - this library is a fairly low-level implementation of the FastCGI protocol. It's not particularly concerned about *where* the FastCGI interactions are coming from, just in decoding/encoding them.

This lib is used in https://github.com/samcday/node-fastcgi-application to make a Node process available to a FastCGI manager.
